name: Deploy to prod
on:
  workflow_dispatch:
    inputs:
      deployment-type:
        description: 'Deployment type'
        required: true
        default: 'dev'
        options:
          - dev
          - staging
          - prod
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Trigger Amplify Build
        run: |
          curl -X POST -d {} "${{ secrets.AMPLIFY_MAIN_BRANCH_WEBHOOK }}" -H "Content-Type:application/json"