name: Deploy to prod
on:
  workflow_dispatch:
    inputs:
      deployment-type:
        description: 'Deployment type'
        required: true
        default: 'dev'
        options:
          - dev
          - staging
          - prod
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Amplify Front-end Redeployment
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -d '{}' \
            https://amplify.us-east-1.amazonaws.com/apps/${{ secrets.AMPLIFY_PROD_APP_ID }}/branches/main/redeploys